### ISSUE TITLE
Unexpected behavior when generating spies

### ISSUE THREAD

**Issue by joshwoods** [seanhenry/SwiftMockGeneratorForXcode#24] opened 2019-06-24 20:01 UTC
Example:

```
protocol UIApplicationInterface: AnyObject {
    func open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey: Any], completionHandler completion: ((Bool) -> Void)?)
}

extension UIApplication: UIApplicationInterface { }

```

Returned generated code:

```
class TestApplication: UIApplicationInterface {
    var invoked = false
    var invokedCount = 0
    func {
        invoked = true
        invokedCount += 1
    }
}

```

Please let me know if there is anything else you'd need from me! :)

**Comment by seanhenry** [comment] 2019-06-26 08:11
Hi @joshwoods 

Thanks for raising this issue. I've been able to reproduce this. It looks like the parser thinks `open` is a keyword and is not parsing the function correctly.

I'm looking into a fix and I will update here when it's ready.

**Comment by seanhenry** [comment] 2019-06-26 16:47
This is now fixed 🎉 You can download the latest version [here](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.20)

**Comment by joshwoods** [comment] 2019-06-26 18:17
oh wow, what a super quick turnaround, thanks @seanhenry!

**Closed as completed** 2019-06-26 18:21 UTC
